[package]
name = "metalfetch"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0"
owo-colors = "4.0"
sysinfo = "0.30"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
